---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcatstart state=stopped
  - name: Check that war file exist
    stat:
      path: /root/apache-tomcat-8.5.76/webapps/hello-world-servlet-example.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /root/apache-tomcat-8.5.76/webapps/hello-world-servlet-example.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /root/apache-tomcat-8.5.76/webapps/hello-world-servlet-example
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /root/apache-tomcat-8.5.76/webapps/hello-world-servlet-example
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://3.19.222.31:8081/nexus/nexus/service/local/artifact/maven/redirect?r=releases&g=com.geekcap.vmturbo&a=hello-world-servlet-example&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.76/webapps/hello-world-servlet-example.war
  - name: Start Tomcat
    service: name=tomcat state=started
